app:
  build: '.'
  environment:
    SECRET:
    GITHUB_TOKEN:
    SLACK_HOOK:
    SLACK_CHANNEL:
    VIRTUAL_HOST: "continuous.*"
    DOMAIN:
    VERBOSE: "1"
  volumes:
    - '/var/run/docker.sock:/var/run/docker.sock'
    - './scripts:/scripts'
