#!/bin/bash

NAME=$(bash /scripts/lib/get-container-name)

docker inspect $NAME > /dev/null 2>&1
if [[ "$?" == 0 ]]; then
  docker stop $NAME > /dev/null 2>&1
  docker rm $NAME > /dev/null 2>&1
  echo "removed $NAME"
fi

#TODO: remove image
