#!/bin/bash

#build repo
IMAGE=$(docker run \
  --rm \
  -e USER=$GITHUB_USER \
  -e REPO=$GITHUB_REPO \
  -e BRANCH=$GITHUB_BRANCH \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v /repos:/repos \
  firstandthird/builder:0.0.5)

if [[ "$?" != 0 ]]; then
  echo "there was an error building"
  #post2slack --tags error --message "$NAME failed to deploy"
  exit 1
fi
echo "$IMAGE built"

NAME=$(bash /scripts/lib/get-container-name)

docker inspect $NAME > /dev/null 2>&1
if [[ "$?" == 0 ]]; then
  echo "$NAME exists, removing first"
  docker stop $NAME
  docker rm $NAME
fi

HOST=$(bash /scripts/lib/get-virtual-host)

docker run -d \
  --name $NAME \
  --env VIRTUAL_HOST=$HOST \
  $IMAGE

if [[ "$?" != 0 ]]; then
  echo "error running $NAME"
  #post2slack --tags error --message "error starting $NAME"
fi

echo "$NAME deployed to $HOST"
#post2slack --tags success --message "$NAME deployed: $HOST"
